---
version: 3

images:
  base_image:
    name: quay.io/ansible/ansible-runner:latest

ansible_config: ansible.cfg

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_files:
  - src: custom_files/
    dest: configs

additional_build_steps:
  prepend_galaxy:
    - RUN echo "Installing Ansible collections..."

  append_final:
    - RUN chmod -R g+w /runner
    - RUN echo "Execution Environment built successfully"

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--pre"

options:
  package_manager_path: /usr/bin/microdnf
  relax_passwd_permissions: true
  user: 1000
  workdir: /runner
